repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1 # Versión actual de Black
    hooks:
      - id: black
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: re-add-staged
        name: Re-add modified files to staged
        entry: git add --update
        language: system
        stages: [pre-commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0 # Usa la última versión disponible
    hooks:
      - id: commitizen
        stages: [commit-msg]
